version: "3"
services:
  app:
    build: .
    image: bzm/server.v0
    ports:
      - "8889:8889"
    volumes:
      - /Users/joe/dev/school_system/src:/app/src
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    entrypoint: ["python3", "app.py"]
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
